version: '3'

services:

  user-identity-service:
    build: ./services/user-identity-service
    command: 'npm run start:address'
    environment:
      - API_PORT=3000
      - API_HOST=0.0.0.0
    networks:
      - bff-example
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

networks:
  bff-example:
