version: '3'

x-domain-service: &domain-service
  environment:
    - API_PORT=3000
    - API_HOST=0.0.0.0
  networks:
    - bff-example
  deploy:
    resources:
      limits:
        cpus: '0.5'
        memory: 128M

services:

  user-identity-service:
    build: ./services/user-identity-service
    <<: *domain-service

  buyer-service:
    build: ./services/buyer-service
    <<: *domain-service

  product-catalog-service:
    build: ./services/product-catalog-service
    <<: *domain-service

networks:
  bff-example:
